apiVersion: apps/v1
kind: Deployment
metadata:
  # Názov Deploymentu s vaším prefixom
  name: xmatuska-ambulance-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      # Unikátny label pre tento Deployment
      pod: xmatuska-ambulance-webapi-label
  template:
    metadata:
      labels:
        # Tento label musí byť zhodný so selector.matchLabels
        pod: xmatuska-ambulance-webapi-label
    spec:
      # Volume, ktorý bude obsahovať inicializačný skript pre Mongo
      volumes:
      - name: init-scripts
        configMap:
          # Názov ConfigMap, ktorá ten skript obsahuje.
          # Tiež musí byť unikátny.
          name: xmatuska-ambulance-webapi-mongodb-init

      # --- INICIALIZAČNÝ KONTAJNER ---
      # Tento kontajner sa spustí a musí úspešne dobehnúť PREDTÝM,
      # ako sa spustia hlavné kontajnery.
      initContainers:
      - name: init-mongodb
        image: mongo:latest # Pre jednoduchosť podľa návodu, inak by tu bola verzia
        imagePullPolicy: Always
        # Príkaz, ktorý sa spustí v kontajneri
        command: ['mongosh', "--nodb", '-f', '/scripts/init-db.js']
        volumeMounts:
        # Pripojenie volume so skriptom do kontajnera
        - name: init-scripts
          mountPath: /scripts
        env:
          # Premenné prostredia potrebné pre inicializačný skript
          - name: AMBULANCE_API_MONGODB_HOST
            value: mongodb
          - name: AMBULANCE_API_MONGODB_PORT
            value: "27017"
          # Tieto hodnoty sa vložia neskôr cez Secrets
          - name: AMBULANCE_API_MONGODB_USERNAME
            value: ""
          - name: AMBULANCE_API_MONGODB_PASSWORD
            value: ""
          # Tieto hodnoty sa vložia z ConfigMap
          - name: AMBULANCE_API_MONGODB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: xmatuska-ambulance-webapi-config
                key: database
          - name: AMBULANCE_API_MONGODB_COLLECTION
            valueFrom:
              configMapKeyRef:
                name: xmatuska-ambulance-webapi-config
                key: collection
          - name: RETRY_CONNECTION_SECONDS
            value: "5"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.01"
          limits:
            memory: "256Mi"
            cpu: "0.1"

      # --- HLAVNÉ KONTAJNERY ---
      # Tieto sa spustia až po úspešnom dokončení initContainers
      containers:
      # 1. Váš aplikačný kontajner
      - name: xmatuska-ambulance-wl-webapi-container
        # Obraz, ktorý ste premenovali
        image: sprowk/xmatuska-webapi:latest
        imagePullPolicy: Always
        ports:
        - name: webapi-port
          containerPort: 8080
        env:
          - name: AMBULANCE_API_ENVIRONMENT
            value: production
          - name: AMBULANCE_API_PORT
            value: "8080"
          - name: AMBULANCE_API_MONGODB_HOST
            value: mongodb
          - name: AMBULANCE_API_MONGODB_PORT
            value: "27017"
          - name: AMBULANCE_API_MONGODB_USERNAME
            value: "" # Bude vložené cez Secret
          - name: AMBULANCE_API_MONGODB_PASSWORD
            value: "" # Bude vložené cez Secret
          - name: AMBULANCE_API_MONGODB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: xmatuska-ambulance-webapi-config
                key: database
          - name: AMBULANCE_API_MONGODB_COLLECTION
            valueFrom:
              configMapKeyRef:
                name: xmatuska-ambulance-webapi-config
                key: collection
          - name: AMBULANCE_API_MONGODB_TIMEOUT_SECONDS
            value: "5"
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.01"
          limits:
            memory: "512Mi"
            cpu: "0.3"
            
      # 2. Sidecar kontajner pre Swagger UI
      - name: openapi-ui
        image: swaggerapi/swagger-ui
        imagePullPolicy: Always
        ports:
        - name: api-ui
          containerPort: 8081
        env:
          - name: PORT
            value: "8081"
          - name: URL
            value: /openapi
          - name: BASE_URL
            value: /openapi-ui
          - name: FILTER
            value: 'true'
          - name: DISPLAY_OPERATION_ID
            value: 'true'
        resources:
          requests:
            memory: "16M"
            cpu: "0.01"
          limits:
            memory: "64M"
            cpu: "0.1"