kind: Service
apiVersion: v1
metadata:
  name: xmatuska-ambulance-webapi
spec:  
  selector:
    pod: xmatuska-ambulance-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80  
    targetPort: webapi-port